/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./settings.html",
    "./insights.html",
    "./garden.html",
    "./src/**/*.{ts,tsx,html}",
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-dim': 'var(--color-surface-dim)',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-error-container': 'var(--color-on-error-container)',
        'tertiary-fixed-dim': 'var(--color-tertiary-fixed-dim)',
        'surface-variant': 'var(--color-surface-variant)',
        'primary-container': 'var(--color-primary-container)',
        'tertiary': 'var(--color-tertiary)',
        'inverse-primary': 'var(--color-inverse-primary)',
        'surface-bright': 'var(--color-surface-bright)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'surface-container': 'var(--color-surface-container)',
        'surface': 'var(--color-surface)',
        'secondary': 'var(--color-secondary)',
        'primary-fixed-dim': 'var(--color-primary-fixed-dim)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-tertiary-fixed': 'var(--color-on-tertiary-fixed)',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'on-error': 'var(--color-on-error)',
        'error': 'var(--color-error)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'outline': 'var(--color-outline)',
        'error-container': 'var(--color-error-container)',
        'background': 'var(--color-background)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'on-tertiary': 'var(--color-on-tertiary)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'on-surface': 'var(--color-on-surface)',
        'on-secondary': 'var(--color-on-secondary)',
        'secondary-fixed-dim': 'var(--color-secondary-fixed-dim)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-primary-fixed': 'var(--color-on-primary-fixed)',
        'primary': 'var(--color-primary)',
        'on-secondary-fixed-variant': 'var(--color-on-secondary-fixed-variant)',
        'on-primary-container': 'var(--color-on-primary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-background': 'var(--color-on-background)',
        'surface-tint': 'var(--color-surface-tint)',
        'surface-container-highest': 'var(--color-surface-container-highest)'
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif']
      }
    },
  },
  plugins: [],
}
