/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./settings.html",
    "./insights.html",
    "./garden.html",
    "./src/**/*.{ts,tsx,html}",
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#763315',
        'surface-dim': '#dddad0',
        'secondary-fixed': '#ffdbce',
        'on-error-container': '#93000a',
        'tertiary-fixed-dim': '#aac8f8',
        'surface-variant': '#e6e2d8',
        'primary-container': '#697b49',
        'tertiary': '#3f5d87',
        'inverse-primary': '#bbce95',
        'surface-bright': '#fdf9ef',
        'on-secondary-fixed': '#370e00',
        'surface-container': '#f1eee4',
        'surface': '#fdf9ef',
        'secondary': '#934a29',
        'primary-fixed-dim': '#bbce95',
        'outline-variant': '#c6c8ba',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#f4f0e7',
        'tertiary-fixed': '#d4e3ff',
        'on-tertiary-fixed': '#001c3a',
        'on-primary-fixed-variant': '#3c4c20',
        'on-error': '#ffffff',
        'error': '#ba1a1a',
        'tertiary-container': '#5876a1',
        'surface-container-low': '#f7f3e9',
        'inverse-surface': '#31312a',
        'outline': '#76786c',
        'error-container': '#ffdad6',
        'background': '#fdf9ef',
        'on-surface-variant': '#45483d',
        'primary-fixed': '#d6eaaf',
        'on-tertiary': '#ffffff',
        'surface-container-high': '#ece8de',
        'on-surface': '#1c1c16',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#ffb598',
        'secondary-container': '#fd9e77',
        'on-tertiary-container': '#fefcff',
        'on-tertiary-fixed-variant': '#284870',
        'on-primary-fixed': '#131f00',
        'primary': '#516233',
        'on-secondary-fixed-variant': '#763314',
        'on-primary-container': '#faffe8',
        'on-primary': '#ffffff',
        'on-background': '#1c1c16',
        'surface-tint': '#546435',
        'surface-container-highest': '#e6e2d8'
      },
      borderRadius: {
        'DEFAULT': '1rem',
        'lg': '2rem',
        'xl': '3rem',
        'full': '9999px'
      },
      fontFamily: {
        'headline': ['Plus Jakarta Sans', 'sans-serif'],
        'body': ['Be Vietnam Pro', 'sans-serif'],
        'label': ['Plus Jakarta Sans', 'sans-serif']
      }
    },
  },
  plugins: [],
}
